language: node_js
node_js:
- '6'
before_script:
- npm install -g gulp-cli
script: npm test
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < ./coverage/lcov.info
- cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
